inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rspec
AllCops:
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
